version: '3.7'

services:

  rancher:
    container_name: rancher
    image: rancher/rancher:latest #v2.4.0
    restart: unless-stopped
    privileged: true #Importante esta parametro
    ports:
      - 80:80
      - 443:443
    volumes:
      - "rancher-data:/var/lib/rancher"
    #environment:
    #  RANCHER_VIRTUAL_HOST: rancher.local
    networks:
      code-network: 
        aliases:
          - rancher.local
    #  VIRTUAL_PORT: 80
volumes:
  rancher-data:
  
networks: 
  code-network:
    name: shared-network