apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: default
  labels:
    app: metabase
data:
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: default
  labels:
    app: metabase
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: metabase
  selector:
    app: metabase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  namespace: default
  labels:
    app: metabase
spec:
  selector:
    matchLabels:
      app: metabase
  replicas: 1
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.44.6"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_JETTY_PORT
            value: "3000"
          - name: MB_DB_TYPE
            value: mysql
          - name: MB_DB_HOST
            value: "mysql"
          - name: MB_DB_PORT
            value: "3306"
          - name: MB_DB_DBNAME
            value: "metabase"
          - name: MB_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: metabase_user
          - name: MB_DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: metabase_pass
          - name: MB_PASSWORD_COMPLEXITY
            value: normal
          - name: MB_PASSWORD_LENGTH
            value: "6"
          - name: JAVA_TIMEZONE
            value: UTC
          - name: MB_EMOJI_IN_LOGS
            value: "true"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
      volumes: