---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: metabase
    
type: Opaque
data:
  root_password: "Y3pDZlVxalRoYkdHVzdBVTRYVjRWWlJzeEs=" #czCfUqjThbGGW7AU4XV4VZRsxK
  metabase_user: "dXNyX21ldGFiYXNl" #usr_metabase
  metabase_pass: "bGFtYW5zeXNfMTIz" #base 64: lamansys_123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-pvc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          args:
          - "--ignore-db-dir=lost+found"
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root_password
          - name: MYSQL_DATABASE
            value: test
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: metabase_user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: metabase_pass
          - name: TZ
            value: UTC-3
          ports:
          - containerPort: 3306
            name: "mysql"
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          resources:
            limits:
              memory: "1G"
              cpu: 0.3
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector: 
    app: mysql
  ports:
  - port: 3306
    name: "mysql"
    protocol: TCP
    targetPort: 3306