apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: curso
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    env:
    - name: ENVIRONMENT
      value: "staging"
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    resources:
      requests: #Inicia Pod, es la garantía
        memory: "64Mi" #MegaB
        cpu: "200m" #200 miliCores, 1 Core -> 1000 miliCores
      limits: #Limitado por el Kernel Linux
        memory: "128Mi"
        cpu: "500m" #Medio Core
    ports:
    - containerPort: 80
 
