apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  mysql.cnf: |
    [client]
    default-character-set=utf8
  
    [mysql]
    default-character-set=utf8
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          root   /usr/share/nginx/html5;
          index  index.html index.htm index.php;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
    }