apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: metabase
    
type: Opaque
data:
  root_password: "Y3pDZlVxalRoYkdHVzdBVTRYVjRWWlJzeEs=" #czCfUqjThbGGW7AU4XV4VZRsxK
  metabase_user: "dXNyX21ldGFiYXNl" #usr_metabase
  metabase_pass: "bGFtYW5zeXNfMTIz" #base 64: lamansys_123